name: gmso-showcase
channels:
  - conda-forge
  - mosdef
  - bioconda
  - omnia
dependencies:
  - python=3.7
  - numpy
  - sympy
  - unyt >= 2.4
  - boltons
  - lxml
  - pytest
  - mbuild >= 0.10.6
  - openbabel >= 3.0
  - foyer
  - gsd >= 2.0
  - parmed
  - pytest-cov
  - codecov
  - pip
  - matplotlib
  - py3Dmol
  - pydantic
  - nodejs>=10
  - gromacs
  - lammps
  - nodejs>=10
  - jupyterlab
  - jupyter-offlinenotebook
  - pocl
  - ipywidgets
  - plotly
  - networkx
  - pandas
  - dash
  - dash-core-components
  - dash-html-components
  - dash_cytoscape
  - dash-table
  - jupyter-dash
  - jupyter-server-proxy
  - pip:
    - "--editable=git+https://github.com/mosdef-hub/gmso.git#egg=gmso-master"
